# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180523_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_perfil', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('metraje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desperdicio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Marco',
        ),
    ]
