# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20180524_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='desperdicio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='metraje',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
