# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180524_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='metraje',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
