# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20180524_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
    ]
