# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20180524_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, default='Sin descripción', max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=productos.models.upload_image_path)),
            ],
        ),
    ]
