# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_modelo_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
