# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_auto_20180525_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
