# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_auto_20180525_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
