# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_modelo_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='modelo_perfil',
            new_name='perfil',
        ),
    ]
