# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=25)),
                ('sexo', models.CharField(max_length=10)),
                ('empresa', models.CharField(max_length=50)),
                ('ejecutivo', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
