# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
